/**
 * The client rolling code must equal the server's, exactly.
 *
 * Every vector below was generated by running
 * `services/core-api/app/services/qr_service.rolling_code` — the same function
 * the scanner validates against. They are not hand-computed and they are not
 * from an RFC: they are the actual output of the actual server, which is the
 * only thing that matters at a gate.
 *
 * This is the highest-stakes test in the pilgrim app. A mismatch produces a
 * code that is well-formed, plausible, and rejected — indistinguishable to the
 * volunteer holding the scanner from a forged pass. The four parameters that
 * have to agree (SHA-256 not SHA-1, 8 digits not 6, a 60-second step not 30,
 * base32 not raw) are each a thing almost every TOTP tutorial gets differently.
 */

import { describe, expect, it } from 'vitest'

import {
  base32Decode,
  buildQrPayload,
  counterFor,
  DIGITS,
  envelopeFromPayload,
  QR_PREFIX,
  rollingCode,
  secondsUntilRotation,
  STEP_SECONDS,
} from './totp'

/** [secret, unix seconds, expected code] — straight from the server. */
const SERVER_VECTORS: Array<[string, number, string]> = [
  ['JBSWY3DPEHPK3PXP', 0, '96023015'],
  ['JBSWY3DPEHPK3PXP', 59, '96023015'],
  ['JBSWY3DPEHPK3PXP', 60, '36344551'],
  ['JBSWY3DPEHPK3PXP', 1234567890, '45806924'],
  ['JBSWY3DPEHPK3PXP', 1893456000, '89128956'],
  ['GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ', 0, '74875740'],
  ['GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ', 59, '74875740'],
  ['GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ', 60, '32247374'],
  ['GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ', 1234567890, '30246158'],
  ['GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ', 1893456000, '89939294'],
  ['MFRGGZDFMZTWQ2LKNNWG23TP', 0, '56476065'],
  ['MFRGGZDFMZTWQ2LKNNWG23TP', 59, '56476065'],
  ['MFRGGZDFMZTWQ2LKNNWG23TP', 60, '52484817'],
  ['MFRGGZDFMZTWQ2LKNNWG23TP', 1234567890, '73245353'],
  ['MFRGGZDFMZTWQ2LKNNWG23TP', 1893456000, '85888872'],
]

describe('rollingCode agrees with the server', () => {
  it.each(SERVER_VECTORS)('%s at %i -> %s', async (secret, unix, expected) => {
    expect(await rollingCode(secret, new Date(unix * 1000))).toBe(expected)
  })
})

describe('the parameters the server pins', () => {
  it('uses a 60-second step and 8 digits', () => {
    // Changing either of these silently invalidates every pass in circulation.
    expect(STEP_SECONDS).toBe(60)
    expect(DIGITS).toBe(8)
    expect(QR_PREFIX).toBe('WV1')
  })

  it('produces exactly eight digits, zero-padded', async () => {
    const code = await rollingCode('JBSWY3DPEHPK3PXP', new Date(0))
    expect(code).toMatch(/^\d{8}$/)
  })

  it('would not match if the digest were SHA-1', async () => {
    // Guards the one substitution a well-meaning refactor would make. If
    // `totp.ts` were switched to SHA-1 the vectors above would all change, so
    // this is really an assertion that they are still being checked.
    const withSha256 = await rollingCode('JBSWY3DPEHPK3PXP', new Date(0))
    expect(withSha256).toBe('96023015')
  })
})

describe('counters and rotation', () => {
  it('holds one code for a whole step', async () => {
    const a = await rollingCode('JBSWY3DPEHPK3PXP', new Date(0))
    const b = await rollingCode('JBSWY3DPEHPK3PXP', new Date(59_000))
    expect(a).toBe(b)
  })

  it('changes at the step boundary', async () => {
    const before = await rollingCode('JBSWY3DPEHPK3PXP', new Date(59_000))
    const after = await rollingCode('JBSWY3DPEHPK3PXP', new Date(60_000))
    expect(before).not.toBe(after)
  })

  it('counts steps from the epoch', () => {
    expect(counterFor(new Date(0))).toBe(0)
    expect(counterFor(new Date(59_000))).toBe(0)
    expect(counterFor(new Date(60_000))).toBe(1)
    expect(counterFor(new Date(120_000))).toBe(2)
  })

  it('reports the seconds left honestly, never zero at the top of a step', () => {
    // The screen shows this as a countdown. Returning 0 for a whole second
    // would read as "expired" while the code is still perfectly valid.
    expect(secondsUntilRotation(new Date(0))).toBe(60)
    expect(secondsUntilRotation(new Date(1_000))).toBe(59)
    expect(secondsUntilRotation(new Date(59_000))).toBe(1)
    expect(secondsUntilRotation(new Date(60_000))).toBe(60)
  })
})

describe('base32Decode', () => {
  it('decodes RFC 4648 vectors', () => {
    const text = (bytes: Uint8Array) => new TextDecoder().decode(bytes)
    expect(text(base32Decode('MY======'))).toBe('f')
    expect(text(base32Decode('MZXQ===='))).toBe('fo')
    expect(text(base32Decode('MZXW6==='))).toBe('foo')
    expect(text(base32Decode('MZXW6YQ='))).toBe('foob')
    expect(text(base32Decode('MZXW6YTB'))).toBe('fooba')
    expect(text(base32Decode('MZXW6YTBOI======'))).toBe('foobar')
  })

  it('tolerates the shapes a secret arrives in', () => {
    // Through a QR, a clipboard and a JSON round trip, a secret picks up case
    // changes, padding and stray whitespace. None of those should break a pass.
    const canonical = base32Decode('MZXW6YTBOI')
    expect(base32Decode('mzxw6ytboi')).toEqual(canonical)
    expect(base32Decode('MZXW6YTBOI======')).toEqual(canonical)
    expect(base32Decode(' MZXW6YTBOI ')).toEqual(canonical)
  })

  it('refuses a character that is not base32', () => {
    // 0, 1 and 8 are deliberately absent from the alphabet. Silently skipping
    // them would decode a corrupted secret into a plausible wrong code.
    expect(() => base32Decode('MZXW6YTB01')).toThrow(/base32/)
  })
})

describe('QR payload assembly', () => {
  it('matches the server format', () => {
    expect(buildQrPayload('ENVELOPE', '12345678')).toBe('WV1~ENVELOPE~12345678')
  })

  it('recovers the envelope from a server payload', () => {
    // We keep the envelope and throw away the server's code — by the time the
    // pilgrim reaches the gate that code is long expired, and only the locally
    // computed one is any use.
    expect(envelopeFromPayload('WV1~abc.def.ghi~87654321')).toBe('abc.def.ghi')
  })

  it('returns null rather than guessing at a malformed payload', () => {
    expect(envelopeFromPayload('')).toBeNull()
    expect(envelopeFromPayload('nonsense')).toBeNull()
    expect(envelopeFromPayload('WV1~only-two-parts')).toBeNull()
    expect(envelopeFromPayload('WV2~envelope~12345678')).toBeNull()
  })
})
