/**
 * The pass's rolling code, computed on the device (Section 4/M1, Section 4/M7).
 *
 * This is the single most important function in the pilgrim app, because it is
 * the one that has to work when nothing else does. A pilgrim standing at the
 * gate with no signal must still be able to show a valid QR — and the QR is
 * `WV1~<envelope>~<rolling_code>`, where the envelope is a signed blob the
 * server issued once and the rolling code changes every sixty seconds.
 *
 * The envelope can be cached. The code cannot: it is time-derived, so it has to
 * be recomputed locally. Hence this file.
 *
 * It must match `services/core-api/app/services/qr_service.py` exactly:
 *
 *   TOTP, **SHA-256** (not the SHA-1 that almost every TOTP tutorial assumes),
 *   8 digits, 60-second step, base32 secret.
 *
 * Getting any one of those wrong produces a code that looks entirely plausible
 * and is rejected at the gate, which is the worst possible failure mode — it is
 * indistinguishable from a forged pass to the volunteer holding the scanner.
 * `totp.test.ts` pins all four against vectors generated by the server's own
 * implementation.
 *
 * Web Crypto is used rather than a library: `crypto.subtle.sign('HMAC', ...)`
 * is available on every browser that can run a service worker, and pulling in
 * a hashing dependency for this would be most of the JS budget.
 */

/** Must equal `qr_service.ROLLING_STEP_SECONDS`. */
export const STEP_SECONDS = 60
/** Must equal `qr_service.ROLLING_DIGITS`. */
export const DIGITS = 8
/** Must equal `qr_service.QR_PREFIX` / `QR_SEPARATOR`. */
export const QR_PREFIX = 'WV1'
export const QR_SEPARATOR = '~'

const BASE32_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'

/**
 * RFC 4648 base32 decode.
 *
 * Padding is stripped and case is normalised because a secret that has been
 * through a QR, a clipboard and a JSON round trip arrives in whatever shape
 * those left it in.
 */
export function base32Decode(secret: string): Uint8Array {
  const clean = secret.toUpperCase().replace(/=+$/, '').replace(/\s+/g, '')

  let bits = 0
  let value = 0
  let index = 0
  const out = new Uint8Array(Math.floor((clean.length * 5) / 8))

  for (const char of clean) {
    const position = BASE32_ALPHABET.indexOf(char)
    if (position === -1) throw new Error(`Not a base32 character: ${char}`)

    value = (value << 5) | position
    bits += 5

    if (bits >= 8) {
      out[index++] = (value >>> (bits - 8)) & 0xff
      bits -= 8
    }
  }

  return out.subarray(0, index)
}

/** The TOTP counter for a given instant. */
export function counterFor(at: Date = new Date(), stepSeconds = STEP_SECONDS): number {
  return Math.floor(at.getTime() / 1000 / stepSeconds)
}

/** Seconds until the current code stops being the current code. */
export function secondsUntilRotation(at: Date = new Date(), stepSeconds = STEP_SECONDS): number {
  const elapsed = Math.floor(at.getTime() / 1000) % stepSeconds
  return stepSeconds - elapsed
}

function counterBytes(counter: number): Uint8Array {
  // Eight-byte big-endian. Written as two 32-bit halves because a JS number
  // cannot hold a 64-bit integer, and `counter` is small enough that the high
  // half is zero until the year 10000 — but writing it explicitly is cheaper
  // than explaining later why the top four bytes were omitted.
  const buffer = new Uint8Array(8)
  const view = new DataView(buffer.buffer)
  view.setUint32(0, Math.floor(counter / 2 ** 32))
  view.setUint32(4, counter >>> 0)
  return buffer
}

/**
 * The rolling code for a pass secret at a given time.
 *
 * Async because Web Crypto is. Callers recompute this on a timer — see
 * `secondsUntilRotation` — rather than caching it, since a stale code is worse
 * than a slow one.
 */
export async function rollingCode(
  secret: string,
  at: Date = new Date(),
  options: { digits?: number; stepSeconds?: number } = {},
): Promise<string> {
  const digits = options.digits ?? DIGITS
  const stepSeconds = options.stepSeconds ?? STEP_SECONDS

  const key = await crypto.subtle.importKey(
    'raw',
    base32Decode(secret) as BufferSource,
    // SHA-256, matching the server. The default in most TOTP code is SHA-1;
    // using it here would produce a well-formed code that always fails.
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  )

  const mac = new Uint8Array(
    await crypto.subtle.sign('HMAC', key, counterBytes(counterFor(at, stepSeconds)) as BufferSource),
  )

  // RFC 4226 dynamic truncation: the low nibble of the last byte picks the
  // offset, and the top bit of the selected word is masked off.
  const offset = (mac[mac.length - 1] ?? 0) & 0x0f
  const binary =
    (((mac[offset] ?? 0) & 0x7f) << 24) |
    (((mac[offset + 1] ?? 0) & 0xff) << 16) |
    (((mac[offset + 2] ?? 0) & 0xff) << 8) |
    ((mac[offset + 3] ?? 0) & 0xff)

  return String(binary % 10 ** digits).padStart(digits, '0')
}

/**
 * Assemble the full QR payload from a cached envelope and a fresh code.
 *
 * The envelope is whatever the server last gave us; it is signed and carries
 * its own expiry, so caching it is safe in a way that caching the code is not.
 */
export function buildQrPayload(envelope: string, code: string): string {
  return `${QR_PREFIX}${QR_SEPARATOR}${envelope}${QR_SEPARATOR}${code}`
}

/**
 * Pull the envelope back out of a payload the server handed us whole.
 *
 * `GET /passes/{id}/qr` returns a complete `WV1~envelope~code`. We keep the
 * envelope and discard the code — by the time the pilgrim is at the gate, that
 * code is long expired and only the locally computed one is any use.
 */
export function envelopeFromPayload(payload: string): string | null {
  const parts = (payload || '').trim().split(QR_SEPARATOR)
  if (parts.length !== 3 || parts[0] !== QR_PREFIX) return null
  return parts[1] ?? null
}
