"""initial schema

Revision ID: 0002_initial_schema
Revises: 0001_extensions
Create Date: 2026-08-23 23:34:04.320366
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0002_initial_schema'
down_revision: str | None = '0001_extensions'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_secrets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('encrypted_phone', sa.Text(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('purge_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_secrets'))
    )
    op.create_index(op.f('ix_contact_secrets_created_at'), 'contact_secrets', ['created_at'], unique=False)
    op.create_index(op.f('ix_contact_secrets_phone_hash'), 'contact_secrets', ['phone_hash'], unique=False)
    op.create_index(op.f('ix_contact_secrets_purge_after'), 'contact_secrets', ['purge_after'], unique=False)
    op.create_table('purge_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('rows_affected', sa.Integer(), nullable=False),
    sa.Column('cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purge_log'))
    )
    op.create_index(op.f('ix_purge_log_executed_at'), 'purge_log', ['executed_at'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_mr', sa.String(length=160), nullable=False),
    sa.Column('origin', sa.String(length=120), nullable=False),
    sa.Column('path', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('total_km', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes'))
    )
    op.create_index(op.f('ix_routes_created_at'), 'routes', ['created_at'], unique=False)
    op.create_index('ix_routes_path', 'routes', ['path'], unique=False, postgresql_using='gist')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('mfa_secret', sa.Text(), nullable=True),
    sa.Column('mfa_enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_phone_hash'), 'users', ['phone_hash'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_mr', sa.String(length=160), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=False),
    sa.Column('capacity_persons', sa.Integer(), nullable=False),
    sa.Column('zone_type', sa.String(length=32), nullable=False),
    sa.Column('parent_zone_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_zone_id'], ['zones.id'], name=op.f('fk_zones_parent_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones')),
    sa.UniqueConstraint('code', name=op.f('uq_zones_code'))
    )
    op.create_index(op.f('ix_zones_created_at'), 'zones', ['created_at'], unique=False)
    op.create_index('ix_zones_geom', 'zones', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_zones_type_active', 'zones', ['zone_type', 'is_active'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('trigger_metric', sa.String(length=40), nullable=False),
    sa.Column('trigger_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('recommended_action_mr', sa.Text(), nullable=True),
    sa.Column('rule_id', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_alerts_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_alerts_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_status_severity_created', 'alerts', ['status', 'severity', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_zone_id'), 'alerts', ['zone_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_actor_created', 'audit_log', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_target_id'), 'audit_log', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_log_trace_id'), 'audit_log', ['trace_id'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('stream_url', sa.Text(), nullable=True),
    sa.Column('homography_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calibrated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_tripwire_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_cameras_zone_id_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras'))
    )
    op.create_index(op.f('ix_cameras_created_at'), 'cameras', ['created_at'], unique=False)
    op.create_index(op.f('ix_cameras_last_heartbeat_at'), 'cameras', ['last_heartbeat_at'], unique=False)
    op.create_index(op.f('ix_cameras_zone_id'), 'cameras', ['zone_id'], unique=False)
    op.create_table('density_readings',
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('person_count', sa.Integer(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=12), nullable=False),
    sa.Column('flow_dx', sa.Float(), nullable=False),
    sa.Column('flow_dy', sa.Float(), nullable=False),
    sa.Column('stagnation_index', sa.Float(), nullable=False),
    sa.Column('counterflow_ratio', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('camera_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_density_readings_zone_id_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'zone_id', name=op.f('pk_density_readings'))
    )
    op.create_index('ix_density_readings_zone_time', 'density_readings', ['zone_id', 'time'], unique=False, postgresql_using='btree')
    op.create_table('dindis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('name_mr', sa.String(length=200), nullable=False),
    sa.Column('leader_name', sa.String(length=120), nullable=False),
    sa.Column('leader_phone_hash', sa.String(length=64), nullable=False),
    sa.Column('expected_count', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('tracking_device_id', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_dindis_route_id_routes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dindis')),
    sa.UniqueConstraint('code', name=op.f('uq_dindis_code'))
    )
    op.create_index(op.f('ix_dindis_created_at'), 'dindis', ['created_at'], unique=False)
    op.create_index(op.f('ix_dindis_route_id'), 'dindis', ['route_id'], unique=False)
    op.create_table('facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_mr', sa.String(length=160), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('notes_mr', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_facilities_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities'))
    )
    op.create_index(op.f('ix_facilities_created_at'), 'facilities', ['created_at'], unique=False)
    op.create_index('ix_facilities_location', 'facilities', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_facilities_type'), 'facilities', ['type'], unique=False)
    op.create_index(op.f('ix_facilities_zone_id'), 'facilities', ['zone_id'], unique=False)
    op.create_table('gates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_mr', sa.String(length=160), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('throughput_per_hour', sa.Integer(), nullable=False),
    sa.Column('is_restricted', sa.Boolean(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_gates_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gates')),
    sa.UniqueConstraint('code', name=op.f('uq_gates_code'))
    )
    op.create_index(op.f('ix_gates_created_at'), 'gates', ['created_at'], unique=False)
    op.create_index('ix_gates_location', 'gates', ['location'], unique=False, postgresql_using='gist')
    op.create_table('halt_towns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_mr', sa.String(length=160), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('expected_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_headcount', sa.Integer(), nullable=True),
    sa.Column('water_points', sa.Integer(), nullable=False),
    sa.Column('sanitation_units', sa.Integer(), nullable=False),
    sa.Column('medical_camps', sa.Integer(), nullable=False),
    sa.Column('readiness_status', sa.String(length=16), nullable=False),
    sa.Column('readiness_note', sa.Text(), nullable=True),
    sa.Column('contacts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_halt_towns_route_id_routes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_halt_towns'))
    )
    op.create_index('ix_halt_towns_centroid', 'halt_towns', ['centroid'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_halt_towns_created_at'), 'halt_towns', ['created_at'], unique=False)
    op.create_index('ix_halt_towns_geom', 'halt_towns', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_halt_towns_route_id'), 'halt_towns', ['route_id'], unique=False)
    op.create_table('responders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('call_sign', sa.String(length=40), nullable=False),
    sa.Column('unit_type', sa.String(length=24), nullable=False),
    sa.Column('current_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_ping_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_responders_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responders')),
    sa.UniqueConstraint('call_sign', name=op.f('uq_responders_call_sign'))
    )
    op.create_index(op.f('ix_responders_created_at'), 'responders', ['created_at'], unique=False)
    op.create_index('ix_responders_location', 'responders', ['current_location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_responders_status'), 'responders', ['status'], unique=False)
    op.create_index(op.f('ix_responders_unit_type'), 'responders', ['unit_type'], unique=False)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_system_config_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_config'))
    )
    op.create_index(op.f('ix_system_config_created_at'), 'system_config', ['created_at'], unique=False)
    op.create_table('dindi_pings',
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dindi_id', sa.UUID(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('speed_kmph', sa.Float(), nullable=True),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dindi_id'], ['dindis.id'], name=op.f('fk_dindi_pings_dindi_id_dindis'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'dindi_id', name=op.f('pk_dindi_pings'))
    )
    op.create_index('ix_dindi_pings_location', 'dindi_pings', ['location'], unique=False, postgresql_using='gist')
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=12), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('reporter_phone_hash', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audio_note_uri', sa.Text(), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sla_breached', sa.Boolean(), nullable=False),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_note', sa.Text(), nullable=True),
    sa.Column('assigned_responder_id', sa.UUID(), nullable=True),
    sa.Column('client_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_incidents_alert_id_alerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_responder_id'], ['responders.id'], name=op.f('fk_incidents_assigned_responder_id_responders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_incidents_reported_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_incidents_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index('ix_incidents_location', 'incidents', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_incidents_reference'), 'incidents', ['reference'], unique=True)
    op.create_index(op.f('ix_incidents_reporter_phone_hash'), 'incidents', ['reporter_phone_hash'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_sla_due_at'), 'incidents', ['sla_due_at'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index('ix_incidents_status_severity_created', 'incidents', ['status', 'severity', 'created_at'], unique=False)
    op.create_index(op.f('ix_incidents_type'), 'incidents', ['type'], unique=False)
    op.create_index(op.f('ix_incidents_zone_id'), 'incidents', ['zone_id'], unique=False)
    op.create_table('slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('booked_count', sa.Integer(), nullable=False),
    sa.Column('walkin_reserve', sa.Integer(), nullable=False),
    sa.Column('walkin_used', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('gate_id', sa.UUID(), nullable=True),
    sa.Column('actual_throughput', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('booked_count + walkin_reserve <= capacity', name=op.f('ck_slots_no_oversubscription')),
    sa.CheckConstraint('booked_count >= 0', name=op.f('ck_slots_booked_count_non_negative')),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], name=op.f('fk_slots_gate_id_gates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slots')),
    sa.UniqueConstraint('date', 'start_time', 'gate_id', name='uq_slot_date_start_gate')
    )
    op.create_index(op.f('ix_slots_created_at'), 'slots', ['created_at'], unique=False)
    op.create_index(op.f('ix_slots_date'), 'slots', ['date'], unique=False)
    op.create_index('ix_slots_date_start', 'slots', ['date', 'start_time'], unique=False)
    op.create_index(op.f('ix_slots_status'), 'slots', ['status'], unique=False)
    op.create_table('tripwires',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('gate_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('restricted_direction', sa.String(length=8), nullable=False),
    sa.Column('active_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_tripwires_camera_id_cameras'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], name=op.f('fk_tripwires_gate_id_gates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tripwires'))
    )
    op.create_index(op.f('ix_tripwires_camera_id'), 'tripwires', ['camera_id'], unique=False)
    op.create_index(op.f('ix_tripwires_created_at'), 'tripwires', ['created_at'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_incident_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_events_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_events'))
    )
    op.create_index(op.f('ix_incident_events_created_at'), 'incident_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    op.create_table('missing_persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_uri', sa.Text(), nullable=True),
    sa.Column('last_seen_zone_id', sa.UUID(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_phone_hash', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_missing_persons_incident_id_incidents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_seen_zone_id'], ['zones.id'], name=op.f('fk_missing_persons_last_seen_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_missing_persons'))
    )
    op.create_index(op.f('ix_missing_persons_created_at'), 'missing_persons', ['created_at'], unique=False)
    op.create_index(op.f('ix_missing_persons_incident_id'), 'missing_persons', ['incident_id'], unique=False)
    op.create_index(op.f('ix_missing_persons_purge_after'), 'missing_persons', ['purge_after'], unique=False)
    op.create_index(op.f('ix_missing_persons_status'), 'missing_persons', ['status'], unique=False)
    op.create_table('passes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=12), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('holder_phone_hash', sa.String(length=64), nullable=False),
    sa.Column('holder_name', sa.String(length=120), nullable=False),
    sa.Column('holder_language', sa.String(length=5), nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=False),
    sa.Column('qr_secret', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scanned_by', sa.UUID(), nullable=True),
    sa.Column('scanned_gate_id', sa.UUID(), nullable=True),
    sa.Column('original_slot_id', sa.UUID(), nullable=True),
    sa.Column('reslot_count', sa.Integer(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('group_size >= 1 AND group_size <= 6', name=op.f('ck_passes_group_size_range')),
    sa.ForeignKeyConstraint(['original_slot_id'], ['slots.id'], name=op.f('fk_passes_original_slot_id_slots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], name=op.f('fk_passes_scanned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scanned_gate_id'], ['gates.id'], name=op.f('fk_passes_scanned_gate_id_gates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], name=op.f('fk_passes_slot_id_slots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passes'))
    )
    op.create_index(op.f('ix_passes_created_at'), 'passes', ['created_at'], unique=False)
    op.create_index(op.f('ix_passes_holder_phone_hash'), 'passes', ['holder_phone_hash'], unique=False)
    op.create_index('ix_passes_phone_status', 'passes', ['holder_phone_hash', 'status'], unique=False)
    op.create_index(op.f('ix_passes_reference'), 'passes', ['reference'], unique=True)
    op.create_index(op.f('ix_passes_slot_id'), 'passes', ['slot_id'], unique=False)
    op.create_index('ix_passes_slot_status', 'passes', ['slot_id', 'status'], unique=False)
    op.create_index(op.f('ix_passes_status'), 'passes', ['status'], unique=False)
    op.create_table('breach_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('tripwire_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('gate_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('crossing_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('clip_uri', sa.Text(), nullable=True),
    sa.Column('clip_sha256', sa.String(length=64), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('chain_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pass_scan_checked', sa.Boolean(), nullable=False),
    sa.Column('matched_pass_id', sa.UUID(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('deletion_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_breach_events_camera_id_cameras'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_breach_events_deleted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], name=op.f('fk_breach_events_gate_id_gates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_pass_id'], ['passes.id'], name=op.f('fk_breach_events_matched_pass_id_passes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_breach_events_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tripwire_id'], ['tripwires.id'], name=op.f('fk_breach_events_tripwire_id_tripwires'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_breach_events')),
    sa.UniqueConstraint('chain_hash', name=op.f('uq_breach_events_chain_hash'))
    )
    op.create_index(op.f('ix_breach_events_created_at'), 'breach_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_breach_events_gate_id'), 'breach_events', ['gate_id'], unique=False)
    op.create_index(op.f('ix_breach_events_occurred_at'), 'breach_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_breach_events_purge_after'), 'breach_events', ['purge_after'], unique=False)
    op.create_index(op.f('ix_breach_events_review_status'), 'breach_events', ['review_status'], unique=False)
    op.create_index(op.f('ix_breach_events_sequence'), 'breach_events', ['sequence'], unique=True)
    op.create_index(op.f('ix_breach_events_tripwire_id'), 'breach_events', ['tripwire_id'], unique=False)
    op.create_index('ix_breach_gate_occurred', 'breach_events', ['gate_id', 'occurred_at'], unique=False)
    op.create_index('ix_breach_review_occurred', 'breach_events', ['review_status', 'occurred_at'], unique=False)
    op.create_table('pass_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pass_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age_band', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['pass_id'], ['passes.id'], name=op.f('fk_pass_members_pass_id_passes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pass_members'))
    )
    op.create_index(op.f('ix_pass_members_pass_id'), 'pass_members', ['pass_id'], unique=False)
    op.create_table('pass_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pass_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=12), nullable=False),
    sa.Column('payload_mr', sa.Text(), nullable=False),
    sa.Column('payload_en', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pass_id'], ['passes.id'], name=op.f('fk_pass_notifications_pass_id_passes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pass_notifications'))
    )
    op.create_index(op.f('ix_pass_notifications_created_at'), 'pass_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_pass_notifications_pass_id'), 'pass_notifications', ['pass_id'], unique=False)
    op.create_index(op.f('ix_pass_notifications_status'), 'pass_notifications', ['status'], unique=False)
    op.create_table('clip_access_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('breach_event_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_clip_access_log_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['breach_event_id'], ['breach_events.id'], name=op.f('fk_clip_access_log_breach_event_id_breach_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clip_access_log'))
    )
    op.create_index(op.f('ix_clip_access_log_accessed_at'), 'clip_access_log', ['accessed_at'], unique=False)
    op.create_index(op.f('ix_clip_access_log_actor_id'), 'clip_access_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_clip_access_log_breach_event_id'), 'clip_access_log', ['breach_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clip_access_log_breach_event_id'), table_name='clip_access_log')
    op.drop_index(op.f('ix_clip_access_log_actor_id'), table_name='clip_access_log')
    op.drop_index(op.f('ix_clip_access_log_accessed_at'), table_name='clip_access_log')
    op.drop_table('clip_access_log')
    op.drop_index(op.f('ix_pass_notifications_status'), table_name='pass_notifications')
    op.drop_index(op.f('ix_pass_notifications_pass_id'), table_name='pass_notifications')
    op.drop_index(op.f('ix_pass_notifications_created_at'), table_name='pass_notifications')
    op.drop_table('pass_notifications')
    op.drop_index(op.f('ix_pass_members_pass_id'), table_name='pass_members')
    op.drop_table('pass_members')
    op.drop_index('ix_breach_review_occurred', table_name='breach_events')
    op.drop_index('ix_breach_gate_occurred', table_name='breach_events')
    op.drop_index(op.f('ix_breach_events_tripwire_id'), table_name='breach_events')
    op.drop_index(op.f('ix_breach_events_sequence'), table_name='breach_events')
    op.drop_index(op.f('ix_breach_events_review_status'), table_name='breach_events')
    op.drop_index(op.f('ix_breach_events_purge_after'), table_name='breach_events')
    op.drop_index(op.f('ix_breach_events_occurred_at'), table_name='breach_events')
    op.drop_index(op.f('ix_breach_events_gate_id'), table_name='breach_events')
    op.drop_index(op.f('ix_breach_events_created_at'), table_name='breach_events')
    op.drop_table('breach_events')
    op.drop_index(op.f('ix_passes_status'), table_name='passes')
    op.drop_index('ix_passes_slot_status', table_name='passes')
    op.drop_index(op.f('ix_passes_slot_id'), table_name='passes')
    op.drop_index(op.f('ix_passes_reference'), table_name='passes')
    op.drop_index('ix_passes_phone_status', table_name='passes')
    op.drop_index(op.f('ix_passes_holder_phone_hash'), table_name='passes')
    op.drop_index(op.f('ix_passes_created_at'), table_name='passes')
    op.drop_table('passes')
    op.drop_index(op.f('ix_missing_persons_status'), table_name='missing_persons')
    op.drop_index(op.f('ix_missing_persons_purge_after'), table_name='missing_persons')
    op.drop_index(op.f('ix_missing_persons_incident_id'), table_name='missing_persons')
    op.drop_index(op.f('ix_missing_persons_created_at'), table_name='missing_persons')
    op.drop_table('missing_persons')
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_created_at'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_tripwires_created_at'), table_name='tripwires')
    op.drop_index(op.f('ix_tripwires_camera_id'), table_name='tripwires')
    op.drop_table('tripwires')
    op.drop_index(op.f('ix_slots_status'), table_name='slots')
    op.drop_index('ix_slots_date_start', table_name='slots')
    op.drop_index(op.f('ix_slots_date'), table_name='slots')
    op.drop_index(op.f('ix_slots_created_at'), table_name='slots')
    op.drop_table('slots')
    op.drop_index(op.f('ix_incidents_zone_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_type'), table_name='incidents')
    op.drop_index('ix_incidents_status_severity_created', table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_sla_due_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_reporter_phone_hash'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_reference'), table_name='incidents')
    op.drop_index('ix_incidents_location', table_name='incidents', postgresql_using='gist')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_dindi_pings_location', table_name='dindi_pings', postgresql_using='gist')
    op.drop_table('dindi_pings')
    op.drop_index(op.f('ix_system_config_created_at'), table_name='system_config')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_responders_unit_type'), table_name='responders')
    op.drop_index(op.f('ix_responders_status'), table_name='responders')
    op.drop_index('ix_responders_location', table_name='responders', postgresql_using='gist')
    op.drop_index(op.f('ix_responders_created_at'), table_name='responders')
    op.drop_table('responders')
    op.drop_index(op.f('ix_halt_towns_route_id'), table_name='halt_towns')
    op.drop_index('ix_halt_towns_geom', table_name='halt_towns', postgresql_using='gist')
    op.drop_index(op.f('ix_halt_towns_created_at'), table_name='halt_towns')
    op.drop_index('ix_halt_towns_centroid', table_name='halt_towns', postgresql_using='gist')
    op.drop_table('halt_towns')
    op.drop_index('ix_gates_location', table_name='gates', postgresql_using='gist')
    op.drop_index(op.f('ix_gates_created_at'), table_name='gates')
    op.drop_table('gates')
    op.drop_index(op.f('ix_facilities_zone_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_type'), table_name='facilities')
    op.drop_index('ix_facilities_location', table_name='facilities', postgresql_using='gist')
    op.drop_index(op.f('ix_facilities_created_at'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_dindis_route_id'), table_name='dindis')
    op.drop_index(op.f('ix_dindis_created_at'), table_name='dindis')
    op.drop_table('dindis')
    op.drop_index('ix_density_readings_zone_time', table_name='density_readings', postgresql_using='btree')
    op.drop_table('density_readings')
    op.drop_index(op.f('ix_cameras_zone_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_last_heartbeat_at'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_created_at'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_audit_log_trace_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_target_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('ix_audit_actor_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_alerts_zone_id'), table_name='alerts')
    op.drop_index('ix_alerts_status_severity_created', table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_zones_type_active', table_name='zones')
    op.drop_index('ix_zones_geom', table_name='zones', postgresql_using='gist')
    op.drop_index(op.f('ix_zones_created_at'), table_name='zones')
    op.drop_table('zones')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_hash'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_routes_path', table_name='routes', postgresql_using='gist')
    op.drop_index(op.f('ix_routes_created_at'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_purge_log_executed_at'), table_name='purge_log')
    op.drop_table('purge_log')
    op.drop_index(op.f('ix_contact_secrets_purge_after'), table_name='contact_secrets')
    op.drop_index(op.f('ix_contact_secrets_phone_hash'), table_name='contact_secrets')
    op.drop_index(op.f('ix_contact_secrets_created_at'), table_name='contact_secrets')
    op.drop_table('contact_secrets')
    # ### end Alembic commands ###

