"""Feature construction for the density forecaster (Section 4/M6, Phase 8).

Two callers build features, and they must build them identically:

* **Training**, from a season generated by the simulation engine (`season.py`).
* **Inference**, from the rolling history the live pipeline has accumulated.

So both go through `build_row` here, over the same `ZoneHistory` type, at the
same one-minute resolution.  A forecaster whose training features are assembled
by different code from its inference features is a forecaster that scores well
in validation and is wrong in the field, and the failure is invisible until the
day it matters.

**Resolution.** History is bucketed to one minute.  The pipeline publishes every
ten seconds, which is the right cadence for an alert and far finer than anything
a 30-minute forecast can use; six one-minute means are a better feature than
thirty-six raw windows, and they are what the training season is aggregated to.

**What Section 4/M6 asks for and what is actually here.**  The spec's feature
list includes Palkhi ETA and weather.  Neither has a source in this system —
Dindi tracking is Phase 9 and no weather feed is configured — so neither is a
feature.  They are *named* in `MISSING_FEATURES` rather than quietly absent,
because a model that reads "no rain" when the truth is "we have no idea whether
it is raining" will be confidently wrong on the day the rain compresses ten lakh
people into the covered corridors.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field
from datetime import UTC, date, datetime, timedelta
from math import cos, pi, sin

#: One bucket per minute, six hours deep — Section 4/M6's "last 6h density
#: series per zone".
BUCKET_SECONDS = 60
HISTORY_MINUTES = 360

#: Below this the lag features are mostly padding and the model is guessing.
#: The engine reports the zone as unavailable rather than predicting from it;
#: see `forecaster.predict_zone`.
MIN_HISTORY_MINUTES = 45

#: Named, not omitted.  Surfaced on `GET /forecast/status` so the gap is visible
#: from outside the process.
MISSING_FEATURES: tuple[str, ...] = (
    "palkhi_eta — Phase 9 (Dindi tracking) is not built, so no arrival time exists to feed in",
    "weather — no weather feed is configured; rain compressing crowds into covered areas is unmodelled",
    "zone_adjacency — the schema has no upstream/downstream graph, so `upstream_proxy` stands in for it",
)

#: The feature vector, in order.  The order is part of the model artefact: a
#: model trained on one ordering and fed another produces confident nonsense, so
#: `forecaster` stores this tuple alongside the boosters and refuses a mismatch.
FEATURE_NAMES: tuple[str, ...] = (
    "horizon_minutes",
    "density_now",
    "density_lag_5",
    "density_lag_15",
    "density_lag_30",
    "density_lag_60",
    "density_mean_15",
    "density_mean_60",
    "density_max_60",
    "density_slope_15",
    "stagnation_now",
    "stagnation_mean_15",
    "counterflow_now",
    "speed_now",
    "hour_sin",
    "hour_cos",
    "days_to_ekadashi",
    "ekadashi_weight",
    "slot_pressure",
    "upstream_proxy",
)


@dataclass(slots=True)
class Bucket:
    """One minute of one zone, as means rather than samples."""

    minute: datetime
    density: float = 0.0
    stagnation: float = 0.0
    counterflow: float = 0.0
    speed: float = 0.0
    samples: int = 0

    def add(self, *, density: float, stagnation: float, counterflow: float, speed: float) -> None:
        """Running mean, so a minute that received four windows and one that
        received six are directly comparable."""
        n = self.samples
        self.density = (self.density * n + density) / (n + 1)
        self.stagnation = (self.stagnation * n + stagnation) / (n + 1)
        self.counterflow = (self.counterflow * n + counterflow) / (n + 1)
        self.speed = (self.speed * n + speed) / (n + 1)
        self.samples = n + 1


def floor_minute(at: datetime) -> datetime:
    return at.replace(second=0, microsecond=0)


@dataclass(slots=True)
class ZoneHistory:
    """Six hours of one-minute buckets for one zone.

    Bounded and in memory, like the publisher's replay buffer and for the same
    reason: this is a feature window, not a datastore.  The durable series lives
    in Timescale, behind the core API, where the engine cannot reach it.

    A restart therefore starts cold, and the forecaster says so rather than
    predicting from four minutes of history.  That is the honest behaviour: the
    alternative is a confident forecast built on nothing, published in the first
    minute after a deploy.
    """

    zone_id: str
    zone_code: str
    buckets: deque[Bucket] = field(default_factory=lambda: deque(maxlen=HISTORY_MINUTES))

    def observe(
        self,
        at: datetime,
        *,
        density: float,
        stagnation: float = 0.0,
        counterflow: float = 0.0,
        speed: float = 0.0,
    ) -> None:
        """Fold one pipeline window into its minute.

        Out-of-order arrivals land in their own minute if it is still the head,
        and are dropped otherwise.  A reading from twenty minutes ago cannot be
        merged into a bucket that has already scrolled past without rewriting
        history, and the replay path in `publisher` already bounds how late a
        reading can be.
        """
        minute = floor_minute(at)
        if self.buckets and minute < self.buckets[-1].minute:
            return
        if not self.buckets or minute > self.buckets[-1].minute:
            self.buckets.append(Bucket(minute=minute))
        self.buckets[-1].add(density=density, stagnation=stagnation, counterflow=counterflow, speed=speed)

    # -- reads ------------------------------------------------------------
    @property
    def minutes(self) -> int:
        return len(self.buckets)

    @property
    def latest(self) -> Bucket | None:
        return self.buckets[-1] if self.buckets else None

    def is_warm(self) -> bool:
        return self.minutes >= MIN_HISTORY_MINUTES

    def _at_lag(self, minutes: int) -> Bucket | None:
        """The bucket `minutes` ago, or None if history does not reach.

        Indexed from the end rather than searched by timestamp: a gap in the
        pipeline leaves missing minutes, and treating "12 buckets back" as "12
        minutes back" across a gap would silently mislabel the lag.  So gaps are
        detected and the lag is refused instead.
        """
        if not self.buckets:
            return None
        target = self.buckets[-1].minute - timedelta(minutes=minutes)
        for bucket in reversed(self.buckets):
            if bucket.minute == target:
                return bucket
            if bucket.minute < target:
                return None
        return None

    def density_at_lag(self, minutes: int) -> float:
        """The reading `minutes` ago, falling back to the oldest one held.

        Falling back rather than zero-filling: a zone whose history is short has
        an unknown past, and zero is a *claim* about it — the claim that it was
        empty, which is the most dangerous available guess.
        """
        bucket = self._at_lag(minutes)
        if bucket is not None:
            return bucket.density
        return self.buckets[0].density if self.buckets else 0.0

    def window(self, minutes: int) -> list[Bucket]:
        return list(self.buckets)[-minutes:] if self.buckets else []

    def mean_density(self, minutes: int) -> float:
        window = self.window(minutes)
        return sum(b.density for b in window) / len(window) if window else 0.0

    def max_density(self, minutes: int) -> float:
        window = self.window(minutes)
        return max((b.density for b in window), default=0.0)

    def mean_stagnation(self, minutes: int) -> float:
        window = self.window(minutes)
        return sum(b.stagnation for b in window) / len(window) if window else 0.0

    def slope(self, minutes: int) -> float:
        """Change in density per minute over the window, by least squares.

        The single most useful feature in the set, and the reason a forecast can
        beat "it will be what it is now": a corridor at 3.0 p/m² and rising 0.1
        a minute is a different situation from one at 3.0 and falling, and they
        are indistinguishable from the current reading alone.
        """
        window = self.window(minutes)
        n = len(window)
        if n < 2:
            return 0.0
        mean_x = (n - 1) / 2.0
        mean_y = sum(b.density for b in window) / n
        numerator = sum((i - mean_x) * (b.density - mean_y) for i, b in enumerate(window))
        denominator = sum((i - mean_x) ** 2 for i in range(n))
        return numerator / denominator if denominator else 0.0


def ekadashi_weight(at: datetime, ekadashi: date) -> float:
    """The Wari calendar as one number.

    Deliberately the same curve the simulation engine uses, because on simulated
    training data any other curve would be the model learning a mistake.  When
    real telemetry replaces the generated season this feature keeps its meaning:
    it is "how big a day is this", and the Wari's answer does not depend on who
    is measuring it.
    """
    days = (at.date() - ekadashi).days
    curve = {-4: 1.4, -3: 1.9, -2: 2.6, -1: 3.8, 0: 5.0, 1: 3.2, 2: 2.2, 3: 1.6, 4: 1.2}
    return curve.get(days, 1.0)


@dataclass(frozen=True, slots=True)
class Context:
    """Inputs that do not come from the zone's own history.

    `slot_pressure` is Section 4/M6's "active pass bookings for upcoming slots",
    fetched from `GET /ingest/context` — the engine holds no database
    credentials, so the number comes to it.
    """

    ekadashi: date
    #: (slot start, persons booked), from the core API.
    slots: tuple[tuple[datetime, int], ...] = ()
    #: Mean density across the other zones this minute — a coarse stand-in for
    #: "inbound flow from upstream zones" while the schema has no adjacency
    #: graph. Named as a proxy in `MISSING_FEATURES`, not dressed up as the
    #: real thing.
    upstream_proxy: float = 0.0

    def pressure_within(self, at: datetime, minutes: int) -> float:
        """People booked into slots starting between now and the horizon.

        Scaled to thousands so it sits in the same numeric range as the density
        features. Gradient boosting does not need scaled inputs, but a feature
        importance table that reads 4200 next to 3.4 is one nobody interrogates.
        """
        end = at + timedelta(minutes=minutes)
        total = sum(count for start, count in self.slots if at <= start <= end)
        return total / 1000.0


def build_row(
    history: ZoneHistory,
    at: datetime,
    horizon_minutes: int,
    context: Context,
) -> list[float]:
    """One feature vector, in `FEATURE_NAMES` order.

    Pure: same history and same moment give the same row, in training and in
    production. That property is what makes the training/inference skew
    impossible rather than merely unlikely.
    """
    hour = at.hour + at.minute / 60.0
    angle = 2.0 * pi * hour / 24.0
    latest = history.latest

    return [
        float(horizon_minutes),
        latest.density if latest else 0.0,
        history.density_at_lag(5),
        history.density_at_lag(15),
        history.density_at_lag(30),
        history.density_at_lag(60),
        history.mean_density(15),
        history.mean_density(60),
        history.max_density(60),
        history.slope(15),
        latest.stagnation if latest else 0.0,
        history.mean_stagnation(15),
        latest.counterflow if latest else 0.0,
        latest.speed if latest else 0.0,
        # Time of day as a pair, not as an integer hour: 23:59 and 00:01 are two
        # minutes apart and the model must not see them as 23 hours apart.
        sin(angle),
        cos(angle),
        float((at.date() - context.ekadashi).days),
        ekadashi_weight(at, context.ekadashi),
        context.pressure_within(at, horizon_minutes),
        context.upstream_proxy,
    ]


def as_dict(row: list[float]) -> dict[str, float]:
    """Feature row keyed by name — for logs and the status endpoint."""
    return dict(zip(FEATURE_NAMES, row, strict=True))


def utcnow() -> datetime:
    return datetime.now(UTC)
