import type { Copy, Language } from '@/types/domain';

export const languages: { id: Language; label: string; native: string; description: string }[] = [
  { id: 'mr', label: 'मराठी', native: 'मराठीत संवाद साधा', description: 'वारीच्या प्रवासासाठी तुमच्या भाषेत मदत' },
  { id: 'hi', label: 'हिंदी', native: 'हिंदी में बात करें', description: 'वारी के दौरान आपकी भाषा में सहायता' },
  { id: 'en', label: 'English', native: 'Talk in English', description: 'Guidance for every step of your Wari' },
];

export const copy: Record<Language, Copy> = {
  mr: {
    greeting: 'नमस्कार! वारीतील तुमच्या प्रवासासाठी मी मदत करण्यास तयार आहे.',
    greetingSub: 'तुम्हाला काय हवे आहे?',
    placeholder: 'तुम्हाला काय हवे आहे ते सांगा...',
    listening: 'ऐकत आहे...',
    understanding: 'समजून घेत आहे...',
    checking: 'तपासत आहे...',
    crowd: 'गर्दी तपासा',
    facility: 'जवळची सुविधा',
    route: 'रस्ता दाखवा',
    temple: 'मंदिर माहिती',
    help: 'मदत हवी',
    settings: 'सेटिंग्ज',
    map: 'नकाशा',
    send: 'पाठवा',
    speak: 'ऐकवा',
    stop: 'थांबवा',
    viewMap: 'नकाशावर पहा',
    viewRoute: 'रस्ता पहा',
    nearby: 'तुमच्या जवळ',
    poorConnection: 'कमकुवत कनेक्शन',
    getStarted: 'सुरू करा',
    chooseLanguage: 'भाषा निवडा',
    continueLabel: 'पुढे चला',
    welcomeDescription: 'गर्दी, मार्ग, सुविधा, मंदिराची माहिती आणि आपत्कालीन मदतीबद्दल विचारा.',
    noMessages: 'तुमचा प्रश्न इथे दिसेल. बोलून किंवा टाइप करून सुरुवात करा.',
    helpTitle: 'तुमच्या मदतीसाठी',
    helpDescription: 'वारीतील सुरक्षित आणि सोपा प्रवास करण्यासाठी WariVerse ला विचारा.',
    emergency: 'आपत्कालीन मदत',
    emergencyPrompt: 'तुम्ही आपत्कालीन परिस्थितीत आहात का?',
    confirmSOS: 'SOS निश्चित करा',
    cancel: 'रद्द करा',
    location: 'तुमचे स्थान',
    allowLocation: 'स्थानाची परवानगी द्या',
    locationDenied: 'चॅट वापरता येईल, पण स्थानाधारित सेवा उपलब्ध नसतील.',
    clearConversation: 'संभाषण पुसा',
    readAloud: 'मोठ्याने वाचा',
    voiceInput: 'आवाज इनपुट',
    language: 'भाषा',
    about: 'WariVerse बद्दल',
    liveMap: 'लाइव्ह नकाशा',
    recenter: 'पुन्हा मध्यभागी',
    recent: 'अलीकडे',
    updated: 'अपडेट',
  },
  hi: {
    greeting: 'नमस्कार! वारी के दौरान आपकी सहायता के लिए मैं तैयार हूँ।',
    greetingSub: 'आपको क्या चाहिए?',
    placeholder: 'बताएं आपको क्या चाहिए...',
    listening: 'सुन रहा हूँ...',
    understanding: 'समझ रहा हूँ...',
    checking: 'जाँच रहा हूँ...',
    crowd: 'भीड़ देखें',
    facility: 'पास की सुविधा',
    route: 'रास्ता दिखाएं',
    temple: 'मंदिर की जानकारी',
    help: 'मदद चाहिए',
    settings: 'सेटिंग्स',
    map: 'नक्शा',
    send: 'भेजें',
    speak: 'सुनें',
    stop: 'रोकें',
    viewMap: 'नक्शे पर देखें',
    viewRoute: 'रास्ता देखें',
    nearby: 'आपके पास',
    poorConnection: 'कमज़ोर कनेक्शन',
    getStarted: 'शुरू करें',
    chooseLanguage: 'भाषा चुनें',
    continueLabel: 'आगे बढ़ें',
    welcomeDescription: 'भीड़, रास्तों, सुविधाओं, मंदिर की जानकारी और आपातकालीन मदद के बारे में पूछें।',
    noMessages: 'आपका सवाल यहाँ दिखाई देगा। बोलकर या टाइप करके शुरुआत करें।',
    helpTitle: 'हम आपकी मदद के लिए हैं',
    helpDescription: 'वारी में सुरक्षित और आसान यात्रा के लिए WariVerse से पूछें।',
    emergency: 'आपातकालीन मदद',
    emergencyPrompt: 'क्या आप आपातकाल में हैं?',
    confirmSOS: 'SOS की पुष्टि करें',
    cancel: 'रद्द करें',
    location: 'आपका स्थान',
    allowLocation: 'स्थान की अनुमति दें',
    locationDenied: 'आप चैट जारी रख सकते हैं, लेकिन स्थान-आधारित सेवाएँ उपलब्ध नहीं होंगी।',
    clearConversation: 'बातचीत साफ़ करें',
    readAloud: 'ज़ोर से पढ़ें',
    voiceInput: 'आवाज़ इनपुट',
    language: 'भाषा',
    about: 'WariVerse के बारे में',
    liveMap: 'लाइव नक्शा',
    recenter: 'फिर से केंद्रित करें',
    recent: 'हाल ही में',
    updated: 'अपडेट',
  },
  en: {
    greeting: 'Namaste! I’m here to help you during your Wari journey.',
    greetingSub: 'What do you need?',
    placeholder: 'Tell me what you need...',
    listening: 'Listening...',
    understanding: 'Understanding...',
    checking: 'Checking...',
    crowd: 'Check crowd',
    facility: 'Nearby facility',
    route: 'Show route',
    temple: 'Temple info',
    help: 'Get help',
    settings: 'Settings',
    map: 'Map',
    send: 'Send',
    speak: 'Read aloud',
    stop: 'Stop',
    viewMap: 'View on map',
    viewRoute: 'View route',
    nearby: 'Near you',
    poorConnection: 'Poor connection',
    getStarted: 'Get started',
    chooseLanguage: 'Choose language',
    continueLabel: 'Continue',
    welcomeDescription: 'Ask anything about crowds, routes, facilities, temple information, and emergency assistance.',
    noMessages: 'Your question will appear here. Start by speaking or typing below.',
    helpTitle: 'Here when you need us',
    helpDescription: 'Ask WariVerse for a safer, easier journey through the Wari.',
    emergency: 'Emergency assistance',
    emergencyPrompt: 'Are you in an emergency?',
    confirmSOS: 'Confirm SOS',
    cancel: 'Cancel',
    location: 'Your location',
    allowLocation: 'Allow location',
    locationDenied: 'You can keep using chat, but location-based services will not be available.',
    clearConversation: 'Clear conversation',
    readAloud: 'Read aloud',
    voiceInput: 'Voice input',
    language: 'Language',
    about: 'About WariVerse',
    liveMap: 'Live map',
    recenter: 'Recenter',
    recent: 'Recent',
    updated: 'Updated',
  },
};

export const suggestionKeys: (keyof Pick<Copy, 'crowd' | 'facility' | 'route' | 'temple' | 'help'>)[] = [
  'crowd',
  'facility',
  'route',
  'temple',
  'help',
];

export function getCopy(language: Language): Copy {
  return copy[language];
}