"""The recommendation rule table (Section 4/M2 step 5, Section 0 rule 3).

Every alert this system raises carries a suggested action, and every suggested
action comes from a numbered rule in this table.  Nothing here is generated by a
language model, and nothing here is generated by the detector.  An operator who
is about to close a gate on ten thousand people gets to see *which rule* said
so, which is what `Alert.rule_id` is for.

Order matters: the list is evaluated top to bottom and the first match wins, so
the most specific and most dangerous condition is first.  A dense crowd that has
stopped moving is not "a high density alert plus a stagnation alert" — it is one
situation with one correct response.

The Marathi is the operational text.  The control room in Pandharpur runs in
Marathi; the English is the translation, not the other way around.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime

from app.models.crowd import AlertSeverity

# Alert type names.  These are stored on the row and switched on by the UI —
# keep them stable.
DENSITY_CRITICAL = "density_critical"
DENSITY_HIGH = "density_high"
STAGNATION = "stagnation"
COUNTERFLOW = "counterflow"
CAMERA_OFFLINE = "camera_offline"

#: Section 4/M2: stagnation only alerts *with* density above this.  A still,
#: empty plaza at 3 a.m. has a stagnation index of 1.0 and means nothing.
STAGNATION_DENSITY_FLOOR = 3.0


@dataclass(frozen=True, slots=True)
class CrowdSignal:
    """The measured state of one zone at one moment, as the rules see it."""

    density: float
    stagnation_index: float
    counterflow_ratio: float
    person_count: int
    confidence: float = 1.0
    zone_name: str = "this zone"
    zone_name_mr: str = "हा विभाग"


@dataclass(frozen=True, slots=True)
class Rule:
    id: str
    alert_type: str
    severity: AlertSeverity
    metric: str
    threshold: float
    matches: Callable[[CrowdSignal, Thresholds], bool]
    action: str
    action_mr: str

    def value_of(self, signal: CrowdSignal) -> float:
        return float(getattr(signal, self.metric))


@dataclass(frozen=True, slots=True)
class Thresholds:
    """Operator-tunable bands, read from `system_config` at evaluation time."""

    density_high: float = 3.5
    density_critical: float = 5.0
    stagnation: float = 0.70
    counterflow: float = 0.35
    #: Section 4/M8: "if actual pace deviates >45 min from schedule, notify the
    #: next halt town".  Tunable because a route's first two days run to a much
    #: looser clock than its last two.
    dindi_deviation_minutes: float = 45.0


RULES: tuple[Rule, ...] = (
    Rule(
        id="R-M2-01",
        alert_type=DENSITY_CRITICAL,
        severity=AlertSeverity.CRITICAL,
        metric="density",
        threshold=5.0,
        matches=lambda s, t: s.density > t.density_critical and s.stagnation_index > t.stagnation,
        action=(
            "Stop intake at the upstream gate now and hold it. Do not push people forward. "
            "Open the nearest exit route and send marshals in from the edges, not the centre. "
            "A dense crowd that has stopped moving is the crush precursor."
        ),
        action_mr=(
            "वरच्या द्वारावरील प्रवेश तात्काळ थांबवा. गर्दीला पुढे ढकलू नका. "
            "जवळचा निर्गमन मार्ग उघडा आणि स्वयंसेवक मध्यातून नव्हे तर कडेने पाठवा. "
            "थांबलेली दाट गर्दी हाच चेंगराचेंगरीचा पूर्वसंकेत आहे."
        ),
    ),
    Rule(
        id="R-M2-02",
        alert_type=DENSITY_CRITICAL,
        severity=AlertSeverity.CRITICAL,
        metric="density",
        threshold=5.0,
        matches=lambda s, t: s.density > t.density_critical,
        action=(
            "Hold intake at the upstream gate and widen the downstream exit. "
            "Announce the hold in Marathi so the crowd knows it is deliberate — "
            "an unexplained stop pushes people forward."
        ),
        action_mr=(
            "वरच्या द्वारावरील प्रवेश थांबवा आणि पुढील निर्गमन रुंद करा. "
            "मराठीत घोषणा करा जेणेकरून थांबा मुद्दाम आहे हे लोकांना कळेल — "
            "कारण न सांगता थांबवल्यास गर्दी पुढे रेटते."
        ),
    ),
    Rule(
        id="R-M2-03",
        alert_type=STAGNATION,
        severity=AlertSeverity.CRITICAL,
        metric="stagnation_index",
        threshold=0.70,
        matches=lambda s, t: s.stagnation_index > t.stagnation and s.density > STAGNATION_DENSITY_FLOOR,
        action=(
            "The queue has stalled while still dense. Find what is blocking the front — "
            "a closed gate, a fallen pilgrim, a bottleneck — before adding anyone behind it. "
            "Throttle intake to half until movement resumes."
        ),
        action_mr=(
            "गर्दी दाट असतानाच रांग थांबली आहे. मागून आणखी लोक सोडण्यापूर्वी पुढे काय अडले आहे ते शोधा — "
            "बंद द्वार, पडलेला यात्रेकरू, किंवा अरुंद जागा. "
            "हालचाल सुरू होईपर्यंत प्रवेश निम्म्यावर आणा."
        ),
    ),
    Rule(
        id="R-M2-04",
        alert_type=COUNTERFLOW,
        severity=AlertSeverity.WARNING,
        metric="counterflow_ratio",
        threshold=0.35,
        matches=lambda s, t: s.counterflow_ratio > t.counterflow,
        action=(
            "Opposing streams are colliding here. Establish one-way flow with barricades "
            "and route returning pilgrims along the alternate path. Turbulence precedes a crush."
        ),
        action_mr=(
            "इथे विरुद्ध दिशेने जाणारे प्रवाह आदळत आहेत. बॅरिकेड लावून एकेरी मार्ग करा "
            "आणि परतणाऱ्या यात्रेकरूंना पर्यायी मार्गाने पाठवा. अशी घुसळण चेंगराचेंगरीच्या आधी होते."
        ),
    ),
    Rule(
        id="R-M2-05",
        alert_type=DENSITY_HIGH,
        severity=AlertSeverity.WARNING,
        metric="density",
        threshold=3.5,
        matches=lambda s, t: s.density > t.density_high,
        action=(
            "Slow intake at the upstream gate by about a quarter and post marshals at the pinch points. "
            "Check that water and shade are reachable without crossing the flow."
        ),
        action_mr=(
            "वरच्या द्वारावरील प्रवेश साधारण एक चतुर्थांश कमी करा आणि अरुंद जागी स्वयंसेवक ठेवा. "
            "गर्दीतून आडवे न जाता पाणी आणि सावली मिळते का ते तपासा."
        ),
    ),
)


#: Not a density rule — raised by the camera watchdog, but it belongs in the
#: same table so every operator-facing action has one home.
CAMERA_OFFLINE_RULE = Rule(
    id="R-M2-06",
    alert_type=CAMERA_OFFLINE,
    severity=AlertSeverity.WARNING,
    metric="confidence",
    threshold=0.0,
    matches=lambda s, t: False,  # dispatched explicitly, never by signal match
    action=(
        "This zone has lost camera coverage. Its density reading is now an estimate, not a measurement. "
        "Post a volunteer to report the zone by radio until the feed returns."
    ),
    action_mr=(
        "या विभागाचे कॅमेरा कव्हरेज गेले आहे. आता गर्दीचा आकडा मोजमाप नसून अंदाज आहे. "
        "फीड परत येईपर्यंत एका स्वयंसेवकाला रेडिओवरून माहिती देण्यासाठी नेमा."
    ),
)


@dataclass(frozen=True, slots=True)
class Recommendation:
    rule: Rule
    trigger_value: float

    @property
    def action(self) -> str:
        return self.rule.action

    @property
    def action_mr(self) -> str:
        return self.rule.action_mr


def evaluate(signal: CrowdSignal, thresholds: Thresholds | None = None) -> Recommendation | None:
    """First matching rule, or None when the zone is behaving.

    One reading produces at most one alert.  Firing three overlapping alerts for
    one stalled corridor is how an alert feed becomes wallpaper, and wallpaper
    is how a real alert gets missed.
    """
    bands = thresholds or Thresholds()
    for rule in RULES:
        if rule.matches(signal, bands):
            return Recommendation(rule=rule, trigger_value=rule.value_of(signal))
    return None


def rule_by_id(rule_id: str) -> Rule | None:
    for rule in (
        *RULES,
        CAMERA_OFFLINE_RULE,
        *(f.as_rule() for f in FORECAST_RULES),
        *(d.as_rule() for d in DINDI_RULES),
        PALKHI_SIGNAL_LOST_RULE,
        PALKHI_OFF_ROUTE_RULE,
    ):
        if rule.id == rule_id:
            return rule
    return None


# ---------------------------------------------------------------------------
# forecast rules (Section 4/M6, Phase 8)
# ---------------------------------------------------------------------------
FORECAST_HIGH = "forecast_high"

#: Below this the interval is too wide to act on.  A prediction of 4.2 p/m²
#: with a band from 1.1 to 7.0 is not a forecast of a crush, it is the model
#: saying it does not know — and holding a gate on that is how operators learn
#: to ignore the forecast strip entirely.
MAX_ACTIONABLE_INTERVAL_WIDTH = 2.5


@dataclass(frozen=True, slots=True)
class ForecastSignal:
    """One prediction, as the rules see it.

    Carries the interval and not just the point estimate, because the rules
    below refuse to fire on a prediction the model is not sure about, and they
    cannot make that judgement from a single number.
    """

    predicted_density: float
    interval_low: float
    interval_high: float
    horizon_minutes: int
    target_at: datetime
    zone_name: str = "this zone"
    zone_name_mr: str = "हा विभाग"
    gate_name: str = "the upstream gate"
    gate_name_mr: str = "वरचे द्वार"

    @property
    def interval_width(self) -> float:
        return self.interval_high - self.interval_low

    @property
    def is_actionable(self) -> bool:
        return self.interval_width <= MAX_ACTIONABLE_INTERVAL_WIDTH


@dataclass(frozen=True, slots=True)
class ForecastRule:
    """A rule whose action carries the forecast's own numbers.

    Unlike the M2 rules, whose actions are fixed sentences, Section 4/M6 asks
    for a *concrete* suggestion — "hold Gate 2 intake for 12 min" — which means
    the numbers have to come from the prediction.  They come from the prediction
    and from the arithmetic below, and from nothing else.  A language model may
    rephrase what this produces; it may not produce it.
    """

    id: str
    severity: AlertSeverity
    threshold: float
    matches: Callable[[ForecastSignal, Thresholds], bool]
    template: str
    template_mr: str

    def as_rule(self) -> Rule:
        """Adapter so `rule_by_id` can resolve forecast rules from an alert row."""
        return Rule(
            id=self.id,
            alert_type=FORECAST_HIGH,
            severity=self.severity,
            metric="density",
            threshold=self.threshold,
            matches=lambda s, t: False,  # dispatched by `evaluate_forecast`, never by CrowdSignal
            action=self.template,
            action_mr=self.template_mr,
        )


def hold_minutes(signal: ForecastSignal, thresholds: Thresholds) -> int:
    """How long to hold intake, in whole minutes.

    Proportional to how far the prediction sits above the band it is crossing,
    and capped at the horizon: a hold longer than the forecast that justified it
    is a hold with no evidence behind its tail.  Rounded up to five-minute steps
    because a gate marshal cannot act on "hold for 7 minutes", and rounding down
    would under-serve the case the rule exists for.
    """
    excess = max(0.0, signal.predicted_density - thresholds.density_high)
    raw = 5.0 + excess * 8.0
    stepped = 5 * int((raw + 4.999) // 5)
    return int(min(stepped, signal.horizon_minutes))


#: Ordered, first match wins — the same contract as `RULES`.
FORECAST_RULES: tuple[ForecastRule, ...] = (
    ForecastRule(
        id="R-M6-01",
        severity=AlertSeverity.CRITICAL,
        threshold=5.0,
        matches=lambda s, t: s.predicted_density > t.density_critical and s.is_actionable,
        template=(
            "{zone_name} is forecast to reach {density:.1f} p/m² by {target:%H:%M} "
            "({low:.1f}-{high:.1f} range, {horizon} min ahead). "
            "Suggested: hold {gate_name} intake for {hold} min starting now, "
            "open the alternate route before the hold rather than after it, and "
            "pause pass releases for the {target:%H:%M} slot. "
            "Acting at the forecast is the only way to act before the density."
        ),
        template_mr=(
            "{zone_name_mr} मध्ये {target:%H:%M} पर्यंत {density:.1f} प्रति चौ.मी. गर्दीचा अंदाज आहे "
            "({low:.1f}-{high:.1f} दरम्यान, {horizon} मिनिटे आधी). "
            "सूचना: {gate_name_mr} वरील प्रवेश आत्तापासून {hold} मिनिटे थांबवा, "
            "थांबवण्यापूर्वीच पर्यायी मार्ग उघडा, आणि {target:%H:%M} च्या स्लॉटचे पास सोडणे थांबवा. "
            "गर्दी होण्याआधी कृती करण्याचा हाच एक मार्ग आहे."
        ),
    ),
    ForecastRule(
        id="R-M6-02",
        severity=AlertSeverity.WARNING,
        threshold=3.5,
        matches=lambda s, t: s.predicted_density > t.density_high and s.is_actionable,
        template=(
            "{zone_name} is forecast to reach {density:.1f} p/m² by {target:%H:%M} "
            "({low:.1f}-{high:.1f} range, {horizon} min ahead). "
            "Suggested: slow {gate_name} intake by about a quarter for {hold} min, "
            "post marshals at the pinch points now, and check the {target:%H:%M} slot "
            "is not releasing more passes than the zone will hold."
        ),
        template_mr=(
            "{zone_name_mr} मध्ये {target:%H:%M} पर्यंत {density:.1f} प्रति चौ.मी. गर्दीचा अंदाज आहे "
            "({low:.1f}-{high:.1f} दरम्यान, {horizon} मिनिटे आधी). "
            "सूचना: {gate_name_mr} वरील प्रवेश {hold} मिनिटांसाठी साधारण एक चतुर्थांश कमी करा, "
            "अरुंद जागी आत्ताच स्वयंसेवक ठेवा, आणि {target:%H:%M} च्या स्लॉटमधून विभाग सामावू शकेल "
            "त्यापेक्षा जास्त पास सुटत नाहीत ना ते तपासा."
        ),
    ),
    #: Fires on an uncertain but alarming prediction, and says so.  Without this
    #: the wide-interval case is silent, and silence reads as "nothing coming".
    #: It recommends *looking*, never holding a gate — an action taken on a
    #: prediction the model cannot stand behind is the thing R-M6-01 refuses.
    ForecastRule(
        id="R-M6-03",
        severity=AlertSeverity.INFO,
        threshold=3.5,
        matches=lambda s, t: s.interval_high > t.density_critical and not s.is_actionable,
        template=(
            "{zone_name} may reach {high:.1f} p/m² by {target:%H:%M}, but the model's range is "
            "{low:.1f}-{high:.1f} — too wide to act on. "
            "Suggested: put eyes on the zone and confirm by radio. Do not hold a gate on this alone."
        ),
        template_mr=(
            "{zone_name_mr} मध्ये {target:%H:%M} पर्यंत {high:.1f} प्रति चौ.मी. पर्यंत गर्दी होऊ शकते, "
            "पण मॉडेलचा अंदाज {low:.1f}-{high:.1f} इतका विस्तृत आहे — यावर कृती करता येणार नाही. "
            "सूचना: विभागावर लक्ष ठेवा आणि रेडिओवरून खात्री करा. फक्त यावरून द्वार थांबवू नका."
        ),
    ),
)


@dataclass(frozen=True, slots=True)
class ForecastRecommendation:
    rule: ForecastRule
    signal: ForecastSignal
    hold_minutes: int
    action: str
    action_mr: str


def evaluate_forecast(
    signal: ForecastSignal, thresholds: Thresholds | None = None
) -> ForecastRecommendation | None:
    """First matching forecast rule with its numbers filled in, or None.

    The trigger and every number in the returned sentence come from this
    function.  Section 4/M6: "An LLM may phrase the recommendation, but the
    trigger and the numbers come from the rules table. Never let a language
    model invent a safety instruction."
    """
    bands = thresholds or Thresholds()
    for rule in FORECAST_RULES:
        if not rule.matches(signal, bands):
            continue
        hold = hold_minutes(signal, bands)
        fields = {
            "zone_name": signal.zone_name,
            "zone_name_mr": signal.zone_name_mr,
            "gate_name": signal.gate_name,
            "gate_name_mr": signal.gate_name_mr,
            "density": signal.predicted_density,
            "low": signal.interval_low,
            "high": signal.interval_high,
            "horizon": signal.horizon_minutes,
            "target": signal.target_at,
            "hold": hold,
        }
        return ForecastRecommendation(
            rule=rule,
            signal=signal,
            hold_minutes=hold,
            action=rule.template.format(**fields),
            action_mr=rule.template_mr.format(**fields),
        )
    return None


# ---------------------------------------------------------------------------
# palkhi deviation rules (Section 4/M8, Phase 9)
# ---------------------------------------------------------------------------
PALKHI_DEVIATION = "palkhi_deviation"
PALKHI_SIGNAL_LOST = "palkhi_signal_lost"
PALKHI_OFF_ROUTE = "palkhi_off_route"

#: A pace estimate built on fewer than this many pings inside the window is a
#: guess about a walking group made from two dots on a map.  It still produces
#: an alert, but a different one — R-M8-04, which asks somebody to phone the
#: Dindi leader rather than telling a town to move its kitchen.
MIN_PACE_SAMPLES = 4


@dataclass(frozen=True, slots=True)
class DindiSignal:
    """One Dindi's progress against its own schedule, as the rules see it.

    `deviation_minutes` is **signed, and the sign is the important part**:
    positive means arriving later than planned, negative means earlier.  It is
    tempting to collapse this to one magnitude against one threshold, and it is
    wrong.  Late means a town waits with the food going cold.  Early means five
    hundred people walk into a town whose water tankers have not arrived — which
    is the failure Section 4/M8 exists to prevent, and the reason the rules
    below are harder on a fast Dindi than on a slow one.
    """

    dindi_name: str
    dindi_name_mr: str
    next_town: str
    next_town_mr: str
    deviation_minutes: float
    planned_arrival: datetime
    eta: datetime
    expected_count: int
    pace_kmph: float
    km_remaining: float
    #: ready | partial | not_ready | unknown, from the halt town's own board.
    next_town_readiness: str = "unknown"
    #: How many pings the pace was averaged over.
    pace_samples: int = 0

    @property
    def is_late(self) -> bool:
        return self.deviation_minutes > 0

    @property
    def is_confident(self) -> bool:
        return self.pace_samples >= MIN_PACE_SAMPLES and self.pace_kmph > 0.5

    @property
    def town_is_ready(self) -> bool:
        return self.next_town_readiness == "ready"


@dataclass(frozen=True, slots=True)
class DindiRule:
    """A deviation rule whose action names the town, the gap and the group size.

    Same contract as `ForecastRule`: every number in the sentence comes from the
    signal and from nothing else.  A halt-town coordinator being told to move an
    overnight kitchen needs to see *why* — "Saswad, 62 min early, 400 walkers" —
    not a fluent sentence about a schedule a model inferred.
    """

    id: str
    severity: AlertSeverity
    matches: Callable[[DindiSignal, Thresholds], bool]
    template: str
    template_mr: str

    def as_rule(self) -> Rule:
        """Adapter so `rule_by_id` resolves a palkhi rule from an alert row."""
        return Rule(
            id=self.id,
            alert_type=PALKHI_DEVIATION,
            severity=self.severity,
            metric="deviation_minutes",
            threshold=Thresholds().dindi_deviation_minutes,
            matches=lambda s, t: False,  # dispatched by `evaluate_dindi`, never by CrowdSignal
            action=self.template,
            action_mr=self.template_mr,
        )


def _breaches(signal: DindiSignal, thresholds: Thresholds) -> bool:
    return abs(signal.deviation_minutes) > thresholds.dindi_deviation_minutes


#: Ordered, first match wins — the same contract as `RULES` and `FORECAST_RULES`.
DINDI_RULES: tuple[DindiRule, ...] = (
    #: The dangerous case, and the reason this module is more than a map with a
    #: dot on it. A Dindi that is early will reach a town before the town is
    #: standing, and the town does not find that out by watching a map.
    DindiRule(
        id="R-M8-01",
        severity=AlertSeverity.CRITICAL,
        matches=lambda s, t: _breaches(s, t) and not s.is_late and not s.town_is_ready and s.is_confident,
        template=(
            "{dindi_name} is running {gap} min AHEAD of schedule and {next_town} is not ready "
            "({readiness}). About {count} walkers will arrive near {eta:%H:%M}, not {planned:%H:%M} — "
            "{km:.0f} km out at {pace:.1f} km/h. "
            "Call the {next_town} coordinator now: water and sanitation have to be standing before "
            "the group arrives, not after. If they cannot be, ask the Dindi leader to hold at the "
            "previous halt rather than walk into an unprepared town."
        ),
        template_mr=(
            "{dindi_name_mr} वेळापत्रकाच्या {gap} मिनिटे पुढे चालत आहे आणि {next_town_mr} अजून तयार नाही "
            "({readiness_mr}). सुमारे {count} वारकरी {planned:%H:%M} ऐवजी {eta:%H:%M} च्या सुमारास पोहोचतील — "
            "{km:.0f} किमी अंतरावर, {pace:.1f} किमी/तास वेगाने. "
            "{next_town_mr} च्या समन्वयकाला आत्ताच फोन करा: गट पोहोचण्यापूर्वी पाणी आणि स्वच्छतागृहे तयार हवीत, "
            "नंतर नाही. ते शक्य नसेल तर दिंडीप्रमुखांना आधीच्या मुक्कामी थांबण्यास सांगा."
        ),
    ),
    DindiRule(
        id="R-M8-02",
        severity=AlertSeverity.WARNING,
        matches=lambda s, t: _breaches(s, t) and not s.is_late and s.is_confident,
        template=(
            "{dindi_name} is running {gap} min ahead of schedule. About {count} walkers will arrive "
            "near {eta:%H:%M} instead of {planned:%H:%M} — {km:.0f} km out at {pace:.1f} km/h. "
            "{next_town} is marked ready; pull the arrangements forward by that much and confirm the "
            "meal and the medical shift start early too."
        ),
        template_mr=(
            "{dindi_name_mr} वेळापत्रकाच्या {gap} मिनिटे पुढे आहे. सुमारे {count} वारकरी "
            "{planned:%H:%M} ऐवजी {eta:%H:%M} च्या सुमारास पोहोचतील — {km:.0f} किमी अंतरावर, "
            "{pace:.1f} किमी/तास वेगाने. {next_town_mr} तयार आहे; सर्व व्यवस्था तेवढ्याच वेळाने आधी घ्या "
            "आणि भोजन व वैद्यकीय पथकाच्या पाळ्याही लवकर सुरू होतील याची खात्री करा."
        ),
    ),
    DindiRule(
        id="R-M8-03",
        severity=AlertSeverity.WARNING,
        matches=lambda s, t: _breaches(s, t) and s.is_late and s.is_confident,
        template=(
            "{dindi_name} is running {gap} min behind schedule. About {count} walkers will arrive near "
            "{eta:%H:%M} instead of {planned:%H:%M} — {km:.0f} km out at {pace:.1f} km/h. "
            "Tell {next_town} to hold the meal and keep the medical camp staffed past its planned "
            "close; a group walking in after dark arrives tired and needs the camp more, not less. "
            "Check with the Dindi leader that the delay is pace and not an incident."
        ),
        template_mr=(
            "{dindi_name_mr} वेळापत्रकाच्या {gap} मिनिटे मागे आहे. सुमारे {count} वारकरी "
            "{planned:%H:%M} ऐवजी {eta:%H:%M} च्या सुमारास पोहोचतील — {km:.0f} किमी अंतरावर, "
            "{pace:.1f} किमी/तास वेगाने. {next_town_mr} ला भोजन थांबवून ठेवण्यास आणि वैद्यकीय शिबिर "
            "ठरलेल्या वेळेनंतरही सुरू ठेवण्यास सांगा; अंधार पडल्यावर पोहोचणारा गट थकलेला असतो आणि "
            "त्याला शिबिराची जास्त गरज असते. उशीर चालण्याच्या वेगामुळे आहे की काही घटना घडली आहे, "
            "हे दिंडीप्रमुखांकडून तपासा."
        ),
    ),
    #: Fires when the schedule has clearly slipped but the pace estimate rests
    #: on too little. Without it the uncertain case is silent, and silence reads
    #: as "on time". It recommends *phoning*, never moving a town's
    #: arrangements — acting on a two-ping pace estimate is exactly what R-M8-01
    #: refuses to do.
    DindiRule(
        id="R-M8-04",
        severity=AlertSeverity.INFO,
        matches=_breaches,
        template=(
            "{dindi_name} looks {gap} min off schedule for {next_town}, but the estimate rests on "
            "{samples} position report(s) and cannot be relied on. "
            "Suggested: phone the Dindi leader and confirm where they actually are. "
            "Do not move {next_town}'s arrangements on this alone."
        ),
        template_mr=(
            "{dindi_name_mr} {next_town_mr} च्या वेळापत्रकापेक्षा {gap} मिनिटे मागे-पुढे दिसते, "
            "पण हा अंदाज केवळ {samples} नोंदींवर आधारित आहे आणि त्यावर विसंबता येणार नाही. "
            "सूचना: दिंडीप्रमुखांना फोन करून ते नेमके कुठे आहेत ते विचारा. "
            "फक्त यावरून {next_town_mr} ची व्यवस्था बदलू नका."
        ),
    ),
)


#: Not deviation rules — dispatched explicitly by the sweep, the way
#: `CAMERA_OFFLINE_RULE` is, but living here so every operator-facing action in
#: this system has exactly one home.
PALKHI_SIGNAL_LOST_RULE = Rule(
    id="R-M8-05",
    alert_type=PALKHI_SIGNAL_LOST,
    severity=AlertSeverity.WARNING,
    metric="confidence",
    threshold=0.0,
    matches=lambda s, t: False,
    action=(
        "This Dindi's tracking phone has stopped reporting. The group is not lost — the phone is. "
        "Its last position is now a historical fact rather than a current one, and the halt town's "
        "arrival estimate should be treated as unknown, not as the last one shown. "
        "Call the Dindi leader; on an 18-day walk the usual cause is a flat battery."
    ),
    action_mr=(
        "या दिंडीच्या ट्रॅकिंग फोनकडून नोंदी येणे बंद झाले आहे. गट हरवलेला नाही — फोन बंद आहे. "
        "शेवटची नोंदवलेली जागा आता सद्यस्थिती नसून जुनी माहिती आहे, त्यामुळे मुक्कामाच्या गावी "
        "पोहोचण्याची वेळ 'माहिती नाही' समजा, शेवटी दाखवलेली वेळ नव्हे. "
        "दिंडीप्रमुखांना फोन करा; १८ दिवसांच्या वाटचालीत बॅटरी संपणे हेच नेहमीचे कारण असते."
    ),
)

PALKHI_OFF_ROUTE_RULE = Rule(
    id="R-M8-06",
    alert_type=PALKHI_OFF_ROUTE,
    severity=AlertSeverity.WARNING,
    metric="confidence",
    threshold=0.0,
    matches=lambda s, t: False,
    action=(
        "This Dindi is reporting from well off the planned route. Confirm with the leader before "
        "treating it as a diversion: the tracking phone travels with one volunteer, and a volunteer "
        "who has walked into a village for supplies is not a procession that has changed its road. "
        "If the route really has changed, the downstream halt towns have to be told in order."
    ),
    action_mr=(
        "ही दिंडी ठरलेल्या मार्गापासून बऱ्याच अंतरावरून नोंद पाठवत आहे. मार्ग बदलला असे मानण्यापूर्वी "
        "दिंडीप्रमुखांकडून खात्री करा: ट्रॅकिंग फोन एका स्वयंसेवकाजवळ असतो, आणि सामान आणण्यासाठी "
        "गावात गेलेला स्वयंसेवक म्हणजे मार्ग बदललेली दिंडी नव्हे. "
        "खरोखर मार्ग बदलला असेल तर पुढील मुक्कामाच्या गावांना क्रमाने कळवावे लागेल."
    ),
)


_READINESS_MR: dict[str, str] = {
    "ready": "तयार",
    "partial": "अंशतः तयार",
    "not_ready": "तयार नाही",
    "unknown": "माहिती नाही",
}


@dataclass(frozen=True, slots=True)
class DindiRecommendation:
    rule: DindiRule
    signal: DindiSignal
    action: str
    action_mr: str

    @property
    def gap_minutes(self) -> int:
        return int(round(abs(self.signal.deviation_minutes)))


def evaluate_dindi(signal: DindiSignal, thresholds: Thresholds | None = None) -> DindiRecommendation | None:
    """First matching deviation rule with its numbers filled in, or None.

    None is the answer for a Dindi inside its threshold, which is most of them
    most of the time — eighteen days of walking produce a great many readings
    that mean "still on schedule", and not one of them should reach an operator.
    """
    bands = thresholds or Thresholds()
    for rule in DINDI_RULES:
        if not rule.matches(signal, bands):
            continue
        fields = {
            "dindi_name": signal.dindi_name,
            "dindi_name_mr": signal.dindi_name_mr,
            "next_town": signal.next_town,
            "next_town_mr": signal.next_town_mr,
            "gap": int(round(abs(signal.deviation_minutes))),
            "planned": signal.planned_arrival,
            "eta": signal.eta,
            "count": signal.expected_count,
            "pace": signal.pace_kmph,
            "km": signal.km_remaining,
            "samples": signal.pace_samples,
            "readiness": signal.next_town_readiness.replace("_", " "),
            "readiness_mr": _READINESS_MR.get(signal.next_town_readiness, signal.next_town_readiness),
        }
        return DindiRecommendation(
            rule=rule,
            signal=signal,
            action=rule.template.format(**fields),
            action_mr=rule.template_mr.format(**fields),
        )
    return None
