"""The recommendation rule table (Section 4/M2 step 5, Section 0 rule 3).

Every alert this system raises carries a suggested action, and every suggested
action comes from a numbered rule in this table.  Nothing here is generated by a
language model, and nothing here is generated by the detector.  An operator who
is about to close a gate on ten thousand people gets to see *which rule* said
so, which is what `Alert.rule_id` is for.

Order matters: the list is evaluated top to bottom and the first match wins, so
the most specific and most dangerous condition is first.  A dense crowd that has
stopped moving is not "a high density alert plus a stagnation alert" — it is one
situation with one correct response.

The Marathi is the operational text.  The control room in Pandharpur runs in
Marathi; the English is the translation, not the other way around.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

from app.models.crowd import AlertSeverity

# Alert type names.  These are stored on the row and switched on by the UI —
# keep them stable.
DENSITY_CRITICAL = "density_critical"
DENSITY_HIGH = "density_high"
STAGNATION = "stagnation"
COUNTERFLOW = "counterflow"
CAMERA_OFFLINE = "camera_offline"

#: Section 4/M2: stagnation only alerts *with* density above this.  A still,
#: empty plaza at 3 a.m. has a stagnation index of 1.0 and means nothing.
STAGNATION_DENSITY_FLOOR = 3.0


@dataclass(frozen=True, slots=True)
class CrowdSignal:
    """The measured state of one zone at one moment, as the rules see it."""

    density: float
    stagnation_index: float
    counterflow_ratio: float
    person_count: int
    confidence: float = 1.0
    zone_name: str = "this zone"
    zone_name_mr: str = "हा विभाग"


@dataclass(frozen=True, slots=True)
class Rule:
    id: str
    alert_type: str
    severity: AlertSeverity
    metric: str
    threshold: float
    matches: Callable[[CrowdSignal, Thresholds], bool]
    action: str
    action_mr: str

    def value_of(self, signal: CrowdSignal) -> float:
        return float(getattr(signal, self.metric))


@dataclass(frozen=True, slots=True)
class Thresholds:
    """Operator-tunable bands, read from `system_config` at evaluation time."""

    density_high: float = 3.5
    density_critical: float = 5.0
    stagnation: float = 0.70
    counterflow: float = 0.35


RULES: tuple[Rule, ...] = (
    Rule(
        id="R-M2-01",
        alert_type=DENSITY_CRITICAL,
        severity=AlertSeverity.CRITICAL,
        metric="density",
        threshold=5.0,
        matches=lambda s, t: s.density > t.density_critical and s.stagnation_index > t.stagnation,
        action=(
            "Stop intake at the upstream gate now and hold it. Do not push people forward. "
            "Open the nearest exit route and send marshals in from the edges, not the centre. "
            "A dense crowd that has stopped moving is the crush precursor."
        ),
        action_mr=(
            "वरच्या द्वारावरील प्रवेश तात्काळ थांबवा. गर्दीला पुढे ढकलू नका. "
            "जवळचा निर्गमन मार्ग उघडा आणि स्वयंसेवक मध्यातून नव्हे तर कडेने पाठवा. "
            "थांबलेली दाट गर्दी हाच चेंगराचेंगरीचा पूर्वसंकेत आहे."
        ),
    ),
    Rule(
        id="R-M2-02",
        alert_type=DENSITY_CRITICAL,
        severity=AlertSeverity.CRITICAL,
        metric="density",
        threshold=5.0,
        matches=lambda s, t: s.density > t.density_critical,
        action=(
            "Hold intake at the upstream gate and widen the downstream exit. "
            "Announce the hold in Marathi so the crowd knows it is deliberate — "
            "an unexplained stop pushes people forward."
        ),
        action_mr=(
            "वरच्या द्वारावरील प्रवेश थांबवा आणि पुढील निर्गमन रुंद करा. "
            "मराठीत घोषणा करा जेणेकरून थांबा मुद्दाम आहे हे लोकांना कळेल — "
            "कारण न सांगता थांबवल्यास गर्दी पुढे रेटते."
        ),
    ),
    Rule(
        id="R-M2-03",
        alert_type=STAGNATION,
        severity=AlertSeverity.CRITICAL,
        metric="stagnation_index",
        threshold=0.70,
        matches=lambda s, t: s.stagnation_index > t.stagnation and s.density > STAGNATION_DENSITY_FLOOR,
        action=(
            "The queue has stalled while still dense. Find what is blocking the front — "
            "a closed gate, a fallen pilgrim, a bottleneck — before adding anyone behind it. "
            "Throttle intake to half until movement resumes."
        ),
        action_mr=(
            "गर्दी दाट असतानाच रांग थांबली आहे. मागून आणखी लोक सोडण्यापूर्वी पुढे काय अडले आहे ते शोधा — "
            "बंद द्वार, पडलेला यात्रेकरू, किंवा अरुंद जागा. "
            "हालचाल सुरू होईपर्यंत प्रवेश निम्म्यावर आणा."
        ),
    ),
    Rule(
        id="R-M2-04",
        alert_type=COUNTERFLOW,
        severity=AlertSeverity.WARNING,
        metric="counterflow_ratio",
        threshold=0.35,
        matches=lambda s, t: s.counterflow_ratio > t.counterflow,
        action=(
            "Opposing streams are colliding here. Establish one-way flow with barricades "
            "and route returning pilgrims along the alternate path. Turbulence precedes a crush."
        ),
        action_mr=(
            "इथे विरुद्ध दिशेने जाणारे प्रवाह आदळत आहेत. बॅरिकेड लावून एकेरी मार्ग करा "
            "आणि परतणाऱ्या यात्रेकरूंना पर्यायी मार्गाने पाठवा. अशी घुसळण चेंगराचेंगरीच्या आधी होते."
        ),
    ),
    Rule(
        id="R-M2-05",
        alert_type=DENSITY_HIGH,
        severity=AlertSeverity.WARNING,
        metric="density",
        threshold=3.5,
        matches=lambda s, t: s.density > t.density_high,
        action=(
            "Slow intake at the upstream gate by about a quarter and post marshals at the pinch points. "
            "Check that water and shade are reachable without crossing the flow."
        ),
        action_mr=(
            "वरच्या द्वारावरील प्रवेश साधारण एक चतुर्थांश कमी करा आणि अरुंद जागी स्वयंसेवक ठेवा. "
            "गर्दीतून आडवे न जाता पाणी आणि सावली मिळते का ते तपासा."
        ),
    ),
)


#: Not a density rule — raised by the camera watchdog, but it belongs in the
#: same table so every operator-facing action has one home.
CAMERA_OFFLINE_RULE = Rule(
    id="R-M2-06",
    alert_type=CAMERA_OFFLINE,
    severity=AlertSeverity.WARNING,
    metric="confidence",
    threshold=0.0,
    matches=lambda s, t: False,  # dispatched explicitly, never by signal match
    action=(
        "This zone has lost camera coverage. Its density reading is now an estimate, not a measurement. "
        "Post a volunteer to report the zone by radio until the feed returns."
    ),
    action_mr=(
        "या विभागाचे कॅमेरा कव्हरेज गेले आहे. आता गर्दीचा आकडा मोजमाप नसून अंदाज आहे. "
        "फीड परत येईपर्यंत एका स्वयंसेवकाला रेडिओवरून माहिती देण्यासाठी नेमा."
    ),
)


@dataclass(frozen=True, slots=True)
class Recommendation:
    rule: Rule
    trigger_value: float

    @property
    def action(self) -> str:
        return self.rule.action

    @property
    def action_mr(self) -> str:
        return self.rule.action_mr


def evaluate(signal: CrowdSignal, thresholds: Thresholds | None = None) -> Recommendation | None:
    """First matching rule, or None when the zone is behaving.

    One reading produces at most one alert.  Firing three overlapping alerts for
    one stalled corridor is how an alert feed becomes wallpaper, and wallpaper
    is how a real alert gets missed.
    """
    bands = thresholds or Thresholds()
    for rule in RULES:
        if rule.matches(signal, bands):
            return Recommendation(rule=rule, trigger_value=rule.value_of(signal))
    return None


def rule_by_id(rule_id: str) -> Rule | None:
    for rule in (*RULES, CAMERA_OFFLINE_RULE):
        if rule.id == rule_id:
            return rule
    return None
